### PR TITLE
Avoid iterating over Tuple to determine length

### PR DESCRIPTION
**Pull request by awmorgan**

### CODE REVIEW

**Comment by orangeduck** [comment]
Thanks for this.

I think the reason I didn't do this originally is that I was scared it would result in double evaluation of `tuple` arguments. So if you did something like `tuple(foo(x), bar(x))` it would result in `foo` and `bar` being evaluated twice. But now I'm not certain if it will be stripped out given `sizeof` is compile-time. Perhaps you can verify this for me?

Thanks in advance,

Dan

**Comment by awmorgan** [comment]
It appears that `sizeof(foo())` will give you the size of the return type of `foo()` and strip out the call of `foo()`.  So it looks like it is safe against duplicate evaluation. 

```
var foo( var x ) {
  static int64_t i = 0;
  i += c_int(x);
  return new(Int, $I(i));
}

var bar( var x ) {
  static int64_t i = 0;
  i -= c_int(x);
  return new(Int, $I(i));
}

int main(int argc, char** argv) {
  var x = $I(1);
  var t = tuple(foo(x), bar(x));
  println("%$", t); // prints: tuple(1, -1)
  t = tuple(foo(x), bar(x));
  println("%$", t); // prints: tuple(2, -2)
  foreach( i in range($I(10)) ) {
    println("%$", tuple(foo(x), bar(x))); // prints: tuple(3, -3) ... tuple(12, -12)
  }
  return 0;
}
```

**Comment by orangeduck** [comment]
Great! Is this ready to merge then?

**Comment by awmorgan** [comment]
hmm maybe not. I just tested with msvc and it gives an error taking sizeof(func()). Maybe it's a gcc/clang extension.

**Pull request closed without merging**
