### PR TITLE
Add CMake Support

### PR DESCRIPTION
**Pull request by xorz57**
# Here is what I did in this pull request
- Moved `Cello.h` one directory deeper.
- Changed `#include "Cello.h"` to `#include <Cello/Cello.h>`.
- Added `.vscode` and `build` directories to `.gitignore`.
- Renamed `ptest.h` and `ptest.c` to `PTest.h` and `PTest.c`.
- Moved `PTest.h` and `PTest.c` under `vendor/PTest` directory.
- Changed the `path` for `test.txt` and `test.bin`.
- Added support for `CMake`

# But why `CMake`?
- Others can use this library without the need to install it.
- Same workflow for everyone.
- Visual Studio 2015 (and later) supports CMake projects.

# TODO
- Add support for intalling the library
- Add support for packaging the library
- Test compilation on Windows OS
- Test compilation on Mac OS
- Test compilation on Linux OS
- Upload screenshots as proof

# Notes
- This is a draft. I just  wanted to let you know what I am working on and I would like to know if it is ok to continue or just abandon `CMake` if you don't like it.
- If you have anything you want to recommend or that doesn't meet your taste, please let me know!

### CODE REVIEW

**Comment by orangeduck** [comment]
Thanks George, this is cool. I should warn you in advance that I am unlikely to merge this into master - not anything to do with the changes which look good - just that I am not a fan of CMake and don't want to change the build system unless I really have to. That said I would be happy to maintain this on a separate branch or your fork.

**Comment by xorz57** [comment]
@orangeduck WOW thats a fast reply! The fact that you are not really a fan of CMake is completely understandable! I blame CMake for that. All versions before 3.x.x were just horrible. The biggest problem is that there is sparse information on the web about modern CMake and how to do it "right" or "the new way" and mostly people (including me) see a lot of scary CMake 2.x.x stuff.

You don't have to replace the existing build system, that's understandable! I just wanted a place to offer cmake support for those interested.

**Comment by xorz57** [comment]
Since this pull-request is not going to be merged, I am going to keep this fork [here](https://github.com/xorz57/Cello). All credit goes to you @orangeduck the original author.

**Comment by tan-wei** [comment]
I would say thanks to @orangeduck and @xorz57. Actually, for CMake user, it would be happy. However, for CMake writer ...

**Comment by xorz57** [comment]
@tan-wei Personally I think that if you follow modern CMake best practices there should be no issue at all for the CMake maintainer.

**Pull request closed without merging**
